//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Denuncias = new HashSet<Denuncia>();
        }
    
        public long CiudadId { get; set; }
        public string Nombre { get; set; }
        public long DepartamentoId { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Denuncia> Denuncias { get; set; }
    }
}
