//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VioMujerEntities : DbContext
    {
        public VioMujerEntities()
            : base("name=VioMujerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MenuImage> MenuImages { get; set; }
        public DbSet<MenuImageItem> MenuImageItems { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Ciudad> Ciudads { get; set; }
        public DbSet<Departamento> Departamentoes { get; set; }
        public DbSet<Information> Information { get; set; }
        public DbSet<View_Denuncia> View_Denuncia { get; set; }
        public DbSet<Denuncia> Denuncias { get; set; }
    
        public virtual ObjectResult<View_Denuncia> DenunciaList(string orderBy, Nullable<bool> descendente, Nullable<int> nRegPerPage, Nullable<int> nPage, string filtro)
        {
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var descendenteParameter = descendente.HasValue ?
                new ObjectParameter("Descendente", descendente) :
                new ObjectParameter("Descendente", typeof(bool));
    
            var nRegPerPageParameter = nRegPerPage.HasValue ?
                new ObjectParameter("nRegPerPage", nRegPerPage) :
                new ObjectParameter("nRegPerPage", typeof(int));
    
            var nPageParameter = nPage.HasValue ?
                new ObjectParameter("nPage", nPage) :
                new ObjectParameter("nPage", typeof(int));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_Denuncia>("DenunciaList", orderByParameter, descendenteParameter, nRegPerPageParameter, nPageParameter, filtroParameter);
        }
    
        public virtual ObjectResult<View_Denuncia> DenunciaList(string orderBy, Nullable<bool> descendente, Nullable<int> nRegPerPage, Nullable<int> nPage, string filtro, MergeOption mergeOption)
        {
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var descendenteParameter = descendente.HasValue ?
                new ObjectParameter("Descendente", descendente) :
                new ObjectParameter("Descendente", typeof(bool));
    
            var nRegPerPageParameter = nRegPerPage.HasValue ?
                new ObjectParameter("nRegPerPage", nRegPerPage) :
                new ObjectParameter("nRegPerPage", typeof(int));
    
            var nPageParameter = nPage.HasValue ?
                new ObjectParameter("nPage", nPage) :
                new ObjectParameter("nPage", typeof(int));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_Denuncia>("DenunciaList", mergeOption, orderByParameter, descendenteParameter, nRegPerPageParameter, nPageParameter, filtroParameter);
        }
    
        public virtual ObjectResult<Usuario> Autenticar(string login, string passWord)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("Autenticar", loginParameter, passWordParameter);
        }
    
        public virtual ObjectResult<Usuario> Autenticar(string login, string passWord, MergeOption mergeOption)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("Autenticar", mergeOption, loginParameter, passWordParameter);
        }
    
        public virtual int ListaPaginada(string orderBy, Nullable<bool> descendente, Nullable<int> nRegPerPage, Nullable<int> nPage, string filtro, string view, string campos, string campoOrderBy)
        {
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var descendenteParameter = descendente.HasValue ?
                new ObjectParameter("Descendente", descendente) :
                new ObjectParameter("Descendente", typeof(bool));
    
            var nRegPerPageParameter = nRegPerPage.HasValue ?
                new ObjectParameter("nRegPerPage", nRegPerPage) :
                new ObjectParameter("nRegPerPage", typeof(int));
    
            var nPageParameter = nPage.HasValue ?
                new ObjectParameter("nPage", nPage) :
                new ObjectParameter("nPage", typeof(int));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            var viewParameter = view != null ?
                new ObjectParameter("View", view) :
                new ObjectParameter("View", typeof(string));
    
            var camposParameter = campos != null ?
                new ObjectParameter("Campos", campos) :
                new ObjectParameter("Campos", typeof(string));
    
            var campoOrderByParameter = campoOrderBy != null ?
                new ObjectParameter("CampoOrderBy", campoOrderBy) :
                new ObjectParameter("CampoOrderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaPaginada", orderByParameter, descendenteParameter, nRegPerPageParameter, nPageParameter, filtroParameter, viewParameter, camposParameter, campoOrderByParameter);
        }
    }
}
