//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncia
    {
        public long DenunciaId { get; set; }
        public Nullable<long> CiudadId { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<long> AtendidoPor { get; set; }
        public string Ubicacion { get; set; }
        public string Telefono { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
