//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Denuncia
    {
        public long DenunciaId { get; set; }
        public long CiudadId { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public string Ciudad { get; set; }
        public Nullable<long> DepartamentoId { get; set; }
        public string Departamento { get; set; }
        public Nullable<long> AtendidoPorId { get; set; }
        public string AtendidoPor { get; set; }
        public int TotalPages { get; set; }
        public int TotalReg { get; set; }
        public string Ubicacion { get; set; }
        public string Telefono { get; set; }
    }
}
